name: "Stale issue handler"
on:
  workflow_dispatch:
  schedule:
    - cron: "* * * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@main
        id: stale
        with:
          stale-pr-message: "This pull request has become stale and will be closed automatically within a period of time. Sorry about that."
          stale-pr-label: "no-pr-activity"
          days-before-stale: 30
          days-before-close: 5
          exempt-issue-labels: "blocked,must,should,keep"
      - name: Print outputs
        run: echo ${{ join(steps.stale.outputs.*, ',') }}
